### PR TITLE
Update for Drone 1.0.0

### PR DESCRIPTION
**Pull request by gillesdemey**
Updates this plugin to be compatible with the newer `1.0.0` `secret.Request` struct.

Updated the tests to reflect the changes and test for invalid / missing input params.

`Gopkg.lock` file contains some unnecessary changes (digests etc.), probably because I have a newer version of `gopkg`.

### CODE REVIEW

**Comment by rvora** [comment]
@gillesdemey is there a plan to merge this into master? or is there a plan to merge this to master? I am seeing the errors "invalid or missing secret key" which I think this PR fixes. Docker image for kubernetes-secret is 5 months old now.

Thanks.

**Comment by gillesdemey** [comment]
I’m not a contributor so this needs to be reviewed and signed off by someone from the Drone team :)

**Comment by bclermont** [comment]
As @bradrydzewski don't merge this, @gillesdemey do you have a docker image with your changes?

**Comment by bclermont** [comment]
I built one at `bclermont/drone-kubernetes-secrets:1.0`

**Pull request merged**
