### PR TITLE
Process v1.0.0 requests

### PR DESCRIPTION
**Pull request by flah00**
v1.0.0 separates name and path

### CODE REVIEW

**Comment by rvora** [comment]
@flah00 did you close this because the changes were made by @bradrydzewski in master? I don't see these changes in master and I am still seeing the same behavior (agent is sending json with "path" and "name" keys for secret whereas plugin is expecting it in secret#key format).

Still seeing "invalid or missing secret key" message.

**Comment by flah00** [comment]
@rvora No, I closed it because I realized https://github.com/drone/drone-kubernetes-secrets/pull/4/files was a fuller solution which also predated my PR. In the end, I built my image and used it, to work around the issue.

**Comment by rvora** [comment]
Ok thanks, I just noticed that PR also, surprised it is still not merged and new official image created. So the official plugin is really broken and we have to build our own image. Ok, will do to unblock myself.

**Comment by rvora** [comment]
I am having trouble building my fork. Is your image available in the docker hub public repo by any chance? I have already wasted 4-5 hours on this and its getting frustrating :(

**Comment by rvora** [comment]
Nevermind, I got the build to work. Thanks anyways.

**Comment by bradrydzewski** [comment]
@flah00 thanks for the patch. I have merged and updated the latest docker image!

**Pull request closed without merging**
